### ISSUE TITLE
VDS-2020-Quickstart-Standard-2020.25.1.3 Doesn't work with Vault 2023

### ISSUE THREAD

**Issue by JO3ATIgh** [koechlm/VDS-Quickstart-2020#6]
Not sure if you're still supporting this, but I'm really interested in being able to Reserve Part numbers via Data Standard.  I've pulled the ReserveNumbers_2020 from here: https://knowledge.autodesk.com/search-result/caas/simplecontent/content/vault-data-standard-2020-reserve-numbers.html

And I've attempted to get the latest VDS-202-QuickStart-Standard-2020.25.1.3.  Per a quick and recent interaction on the AutoDesk Knowledge Network, I was told that this version should theoretically still work with Vault 2023, but I've had no luck.  When I click Tools > Reserve Numbers, nothing happens.

**Comment by koechlm** [comment]
Thank you for your interest in this tool.
This tool is supported in newer Vault releases and integrated into a full configuration sample. GoTo https://github.com/koechlm/VDS-Sample-Configuration-2023/releases/latest. I hope this helps.

**Comment by JO3ATIgh** [comment]
I greatly appreciate your support.

Following the same instructions that I'd found for the ReserveNumbers version, when I attempted to use the Reserve Numbers tool, I receive the following error message:
***@***.***

V/R,

Joe

**Comment by koechlm** [comment]
Hello Joe, I didn't get the error message with our reply. However, I found an issue and updated the file https://github.com/koechlm/VDS-Sample-Configuration-2023/blob/2023.2.Themed/VDS-2023-MFG-Sample/Vault.Custom/addinVault/ADSK.QS.Default.ps1. I guess you run into the problem solved with this fix.

**Comment by JO3ATIgh** [comment]
Thanks Markus,

Since my screenshot didn't carry over, here's the text of the error message:

DataStandard Powershell Error

Error occurred while executing powershell function InitializeWindow

C:\ProgramData\AutoDesk\Vault 2023\Extensions\DataStandard\Vault.Custom\addinVault\ADSK.QS.Default.ps1
Index operation failed; the array index evaluated to null.

At C:\ProgramData\AutoDesk\Vault 2023\Extensions\DataStandard\Vault.Custom\addinVault\ADSK.QS.Default.ps1:245 char:2
+     $Prop[$nameProp].CustomValidation = {NameCustomValidation}
+

I used Windows PowerShell to modify ADSK.QS.Default with the updated code that you provided in your link and that appears to have solved the problem!

Thank you for your support.  I really appreciate the tool.  Is there instructions on how to integrate the other tools you've provided?  I don't need them, but would love to have the opportunity to use them.  It appears (at least on cursory glance) that your HelpFiles only really explain the function of the add-ins, and not the integration of them.  The only reason I got this far was due to the instructions that were previously included with the ReserveNumbers_2020 that I was able to find-I just followed those instructions and copied over the same folders, PropertyTranslations and UIStrings.

Thanks again

Joe

**Comment by koechlm** [comment]
Hi Joe,
your error has been exactly the fixed one. 
Regarding your other comments: 
- the help is meant as a sample of how to implement a custom help for individual customizations; it is not administrative help.
- I am about to write documentation on how to copy and integrate features from the complete sample to an individual environment. I started with the latest tools but need to catch up with the legacy ones. You inspired me to speed up doing this ;).
Thank you for your valuable feedback!
Cheers,
Markus
